apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-apps
  namespace: flux-system
interval: 5m0s
resources:
  - infrastructure.yaml
  - apps.yaml
  - policy.yaml
  - network-config.yaml