apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config
  namespace: flux-system
data:
  EXTERNAL_ACCESS_CIDR: "192.168.8.0/24"
  
  KUBERNETES_API_CIDR: "192.168.8.226/32"
  KUBERNETES_API_PORT: "6443"

  ENVOY_EXTERNAL_IP: "192.168.8.55"
  ENVOY_HOSTNAME: "gateway.homelab"

  VAULT_EXTERNAL_IP: "192.168.8.60"
  VAULT_HOSTNAME: "vault.homelab"

  MEMCACHED_EXTERNAL_IP: "192.168.8.55"