apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config
  namespace: flux-system
data:
  EXTERNAL_ACCESS_CIDR: "192.168.8.0/24"
  
  KUBERNETES_API_CIDR: "192.168.8.226/32"
  KUBERNETES_API_PORT: "6443"

  CLUSTER_DOMAIN: "homelab"

  OIDC_GATEWAY_IP: "192.168.8.55"
  INTERNAL_GATEWAY_IP: "192.168.8.56"
  GATEWAY_HOSTNAME: "gateway.homelab"
  VECTOR_HOSTNAME: "metrics.homelab"

  VAULT_EXTERNAL_IP: "192.168.8.60"
  VAULT_HOSTNAME: "vault.homelab"

  MEMCACHED_EXTERNAL_IP: "192.168.8.65"