apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-secrets-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-operator
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow reading secrets from Vault
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - port: 8200
          protocol: TCP
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP