apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: grafana
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: grafana
    sectionName: service
  validation:
    caCertificateRefs:
    - name: vault-issuer-ca
      group: ''
      kind: ConfigMap
    hostname: rpi5-1