apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-tls
  duration: 720h # 30 days
  renewBefore: 168h # 7 days
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  commonName: grafana.grafana.svc.cluster.local
  dnsNames:
    - grafana
    - grafana.grafana
    - grafana.grafana.svc
    - grafana.grafana.svc.cluster.local
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: ""