apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - service-account.yaml

labels:
  - pairs:
      app.kubernetes.io/name: registry
    includeSelectors: true 