apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-gateway
spec:
  podSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: internal-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow cluster LAN devices to connect externally
    - from:
        - ipBlock:
            cidr: ${EXTERNAL_ACCESS_CIDR}
      ports:
        - port: 10080
          protocol: TCP
  egress:
    # Allow forwarding gRPC traffic to Vector backend
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vector
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vector
      ports:
        - port: 50051
          protocol: TCP
    # Allow DNS queries to kube-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53