apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: api-gateway
  namespace: envoy
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: "Homelab"
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: https
      protocol: HTTPS
      hostname: rpi5-1
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: gateway-listener-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway_access: "true"