apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy
resources:
  - gateway/oidc/envoy-proxy.yaml
  - gateway/oidc/gateway-class.yaml
  - gateway/oidc/gateway.yaml
  - gateway/oidc/http-route.yaml
  - gateway/oidc/security-policy.yaml
  - gateway/oidc/backend.yaml
  - gateway/oidc/vault-secrets.yaml
  - gateway/oidc/network-policy.yaml

  - gateway/internal/envoy-proxy.yaml
  - gateway/internal/gateway-class.yaml
  - gateway/internal/gateway.yaml
  - gateway/internal/network-policy.yaml
  
  - certificates/envoy-certificate.yaml
  - certificates/issuer-rbac.yaml
  - certificates/issuer.yaml
  - certificates/gateway-certificate.yaml
  - certificates/rate-limit-certificate.yaml