apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy
resources:
  - gateway/envoy-proxy.yaml
  - gateway/gateway-class.yaml
  - gateway/gateway.yaml
  - gateway/http-route.yaml
  - gateway/security-policy.yaml
  - gateway/vault-external-backend.yaml
  - gateway/vault-secrets.yaml
  
  - certificates/envoy-certificate.yaml
  - certificates/envoy-issuer-rbac.yaml
  - certificates/envoy-issuer.yaml
  - certificates/gateway-certificate.yaml
  - certificates/rate-limit-certificate.yaml