apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
  - helm-repository.yaml
  - vault-helm.yaml
  - secrets-operator-helm.yaml
  - secrets-operator-sa.yaml
  - secrets-operator-auth.yaml