apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memcached
resources:
  - service.yaml
  - daemonset.yaml

configMapGenerator:
  - name: proxy-config
    files:
      - config.lua

labels:
  - pairs:
      app.kubernetes.io/name: memcached-proxy
    includeSelectors: true
    includeTemplates: true