apiVersion: v1
kind: Service
metadata:
  name: cache-proxy
  annotations:
    metallb.io/loadBalancerIPs: ${MEMCACHED_EXTERNAL_IP}
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      port: 11211