apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: influxdb
resources:
  - namespace.yaml
  - vault-secrets.yaml
  - certificate.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - network-policy.yaml