apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    isDefault: true
    uid: influxdb
    url: https://influxdb-influxdb2.influxdb.svc.cluster.local:8086
    secureJsonData:
      httpHeaderValue1: "Token $INFLUXDB_READ_TOKEN"
      tlsCACert: |
        $VAULT_ISSUER_CA
    jsonData:
      httpHeaderName1: Authorization
      dbName: data
      tlsAuthWithCACert: true