apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - cert-manager-helm.yaml
  - trust-manager-helm.yaml
  - cluster-issuer-sa.yaml
  - rbac.yaml
  - cert-manager-secret.yaml
  - trust-manager-secret.yaml
  - cluster-issuer.yaml
  - trust-bundle.yaml