apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: envoy-gateway
spec:
  podSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: api-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow cluster LAN devices to connect externally
    - from:
        - ipBlock:
            cidr: 192.168.8.0/24
      ports:
        - port: 10443
          protocol: TCP
  egress:
    # Allow sending OIDC auth requests to Vault
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - port: 8200
          protocol: TCP
    # Allow forwarding traffic to Grafana backend
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: grafana
      ports:
        - port: 3000
          protocol: TCP
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP