apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: envoy-gateway
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: envoy-gateway
    serviceAccount: envoy-gateway
    audiences:
      - vault://envoy/envoy-gateway
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: envoy-gateway-oidc
spec:
  type: kv-v2
  mount: kv
  path: envoy/envoy-gateway/oidc
  destination:
    name: envoy-gateway-oidc
    create: true
  refreshAfter: 30s
  vaultAuthRef: envoy-gateway