apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: vault-external
spec:
  endpoints:
    - fqdn:
        hostname: 'vault.homelab'
        port: 8200
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: vault-external
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: vault-external
  validation:
    caCertificateRefs:
      - name: vault-server-ca
        group: ""
        kind: Secret
    hostname: vault.homelab