apiVersion: v1
kind: Service
metadata:
  name: vector
spec:
  type: NodePort
  ports:
    - name: vector-forwarding
      protocol: TCP
      port: 8222
      targetPort: 8222
      nodePort: 32004
    - name: statsd
      protocol: UDP
      port: 9000