apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cert-manager
    serviceAccount: cert-manager
    audiences:
      - vault://cert-manager/cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cert-manager-ca-bundle
  namespace: cert-manager
spec:
  type: kv-v2
  mount: kv
  path: cert-manager/cert-manager/ca-bundle
  destination:
    name: vault-ca
    create: true
  refreshAfter: 30s
  vaultAuthRef: cert-manager