apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - cert-manager-vault-secrets.yaml
  - cluster-issuer-rbac.yaml
  - cluster-issuer.yaml
  - trust-bundle.yaml
  - trust-manager-vault-secrets.yaml