apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: trust-manager
  namespace: trust-manager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: trust-manager
    serviceAccount: trust-manager
    audiences:
      - vault://trust-manager/trust-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trust-manager-vault-issuer-ca-bundle
  namespace: trust-manager
spec:
  type: kv-v2
  mount: kv
  path: trust-manager/trust-manager/vault-issuer-ca-bundle
  destination:
    name: vault-issuer-ca-bundle-source
    create: true
  refreshAfter: 30s
  vaultAuthRef: trust-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trust-manager-vault-server-ca-bundle
  namespace: trust-manager
spec:
  type: kv-v2
  mount: kv
  path: trust-manager/trust-manager/vault-server-ca-bundle
  destination:
    name: vault-server-ca-bundle-source
    create: true
  refreshAfter: 30s
  vaultAuthRef: trust-manager