apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: "10.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    admin:
      existingSecret: grafana-auth
    service:
      port: 3000
      type: LoadBalancer
    readinessProbe:
      httpGet:
        path: /api/health
        port: grafana
        scheme: HTTPS
    livenessProbe:
      httpGet:
        path: /api/health
        port: grafana
        scheme: HTTPS
      initialDelaySeconds: 60
      timeoutSeconds: 30
      failureThreshold: 10
    extraSecretMounts:
      - name: grafana-tls
        mountPath: /etc/grafana/certs
        secretName: grafana-tls
        readOnly: true
        optional: false
        subPath: ""
    persistence:
      enabled: true
      size: 8Gi
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
        labelValue: "yes"
    grafana.ini:
      server:
        serve_from_sub_path: true
        domain: "rpi5-1"
        root_url: "https://rpi5-1/grafana"
        protocol: https
        cert_key: /etc/grafana/certs/tls.key
        cert_file: /etc/grafana/certs/tls.crt