apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: grafana
    serviceAccount: grafana
    audiences:
      - vault://grafana/grafana
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-auth
spec:
  type: kv-v2
  mount: kv
  path: grafana/grafana/auth
  destination:
    name: grafana-auth
    create: true
  refreshAfter: 30s
  vaultAuthRef: grafana
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-datasources
spec:
  type: kv-v2
  mount: kv
  path: grafana/grafana/datasources
  destination:
    name: grafana-datasources
    create: true
    labels:
      grafana_datasource: "yes"
  refreshAfter: 30s
  vaultAuthRef: grafana