apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-issuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-issuer
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['envoy-issuer']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy-issuer
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: envoy-issuer