apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: envoy-issuer
spec:
  vault:
    path: pki-int/sign/envoy-issuer
    server: https://vault.vault.svc.cluster.local:8200
    serverName: vault.vault
    caBundleSecretRef:
      name: vault-server-ca
    auth:
      kubernetes:
        role: envoy-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: envoy-issuer