apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-rate-limit
  labels:
    app.kubernetes.io/name: envoy-gateway
spec:
  commonName: "*"
  dnsNames:
  - "*.envoy"
  usages:
  - "digital signature"
  - "data encipherment"
  - "key encipherment"
  - "content commitment"
  secretName: envoy-rate-limit
  issuerRef:
    kind: Issuer
    name: envoy-issuer